spring:
  application:
    name: skillbridge

  datasource:
    url: jdbc:sqlserver://aci-sqlskillbridge.eastus.azurecontainer.io:1433;databaseName=db_skillbridge;encrypt=true;trustServerCertificate=true;loginTimeout=30;
    username: sa
    password: "Fiap@skillbridge2025"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect

  sql:
    init:
      mode: never

  redis:
    ssl:
      enabled: true
    url: ${UPSTASH_REDIS_URL}
    password: ${UPSTASH_REDIS_PASSWORD}

server:
  port: 8080
